feat: 기자재 조회/메인 페이지 마크업
jnu-resellers/resellers-fe pull request #11
Opened 2024-04-10 08:49 UTC by mlnwns

![image](https://github.com/jnu-resellers/resellers-fe/assets/129190157/4b57cbe8-65c1-428d-a324-be9cb8072e4f)
- 목업 데이터를 활용해 피드 컴포넌트를 표시했습니다.
- Charkra UI를 사용해보았습니다.
- 상품명이 15글자보다 길어지면 생략되도록 했습니다.

2024-04-11 02:17 UTC, 2yunseong requested changes

2024-04-11 02:17 UTC, 2yunseong commented on src/components/MainFeed.jsx
> +import React, { useState, useEffect } from 'react';
React는 지워볼까요?

2024-04-11 02:17 UTC, 2yunseong commented on src/components/MainFeed.jsx
> +  }, []);
나중에 쿼리로 바꿔봅시다

2024-04-11 12:53 UTC, mlnwns commented on src/components/MainFeed.jsx
> +  }, []);
피드백 받고 쿼리 적용해보려고 인터넷에서 자료 찾아보고 따라하다가 오류가 발생해서 코드 다시 되돌렸습니다ㅠㅠ
리액트 쿼리 사용해보고 싶었어서 시험 끝난 후에 제대로 공부해보고 다시 적용해보겠습니다!

2024-04-12 04:56 UTC, 2yunseong approved these changes

2024-04-12 15:55 UTC, merged