feat: 기자재 거래 정보 페이지 마크업
jnu-resellers/resellers-fe pull request #13
Opened 2024-04-11 11:18 UTC by mlnwns

- Charkra UI를 사용해 마크업 하였습니다.
- 버튼 클릭 시 홈으로 이동하도록 하였습니다.

2024-04-11 11:39 UTC, 2yunseong requested changes

2024-04-11 11:39 UTC, 2yunseong commented on src/components/TransactionInformation/SellerInformation.jsx
> +              <Td textAlign="right">010-0000-0000</Td>
하드 코딩된 값들을 상수로 빼세요~! 입금액에는 `TODO` 주석을 남겨놔도 좋을듯합니다.

2024-04-11 11:39 UTC, 2yunseong commented on src/components/TransactionInformation/ProductInformation.jsx
> +            </Tr>
서버 데이터가 올 곳이니 `TODO`로 남겨두세요. (아래 총 금액도 포함입니다.)

2024-04-11 11:39 UTC, 2yunseong commented on src/components/TransactionInformation/ProductInformation.jsx
> +import React from 'react';
React 빼세요~

2024-04-11 12:50 UTC, mlnwns commented on src/components/TransactionInformation/SellerInformation.jsx
> +              <Td textAlign="right">010-0000-0000</Td>
TODO 주석 남기는 부분에서 은행명이나 계좌번호, 예금주, 연락수단도 판매자가 상품 등록 할 때 작성하고 서버에 올린 데이터라 받아와야 할 거 같은데 이 부분도 TODO 주석 남겨놓으면 좋은 걸까요?

2024-04-11 12:53 UTC, 2yunseong requested changes
리뷰 요청 다시 주셨는데 관련 커밋이 없어서 추가하시고 다시 주세요~

2024-04-11 12:53 UTC, 2yunseong commented on src/components/TransactionInformation/SellerInformation.jsx
> +              <Td textAlign="right">010-0000-0000</Td>
네~ 좋습니다 mock data 사용해서 작성해놔도 좋을 듯 하네요!

2024-04-11 13:45 UTC, mlnwns commented on src/components/TransactionInformation/ProductInformation.jsx
> +            </Tr>
TODO로 주석 처음 남겨봤는데, 이렇게 하는게 맞는지 모르겠습니다..! 상수 부분에다가 해도 되는걸까요?

2024-04-11 14:20 UTC, 2yunseong commented on src/components/TransactionInformation/ProductInformation.jsx
> +            </Tr>
잘 하셨습니다~ vsc extension으로 TodoTree 설치하면 Todo를 확인할 수 있기 때문에 잘 붙이셨습니다.
어차피 서버 데이터 작업을 하게되면 일괄적으로 작업하게 될테니 추후에는 이런식으로 붙이셔도 좋을듯하네요!
```ts
// TODO:  하드코딩된 값 제거 후 API 연동 필요
const SOME_CONSTANTS = { ... }
```

2024-04-12 04:55 UTC, 2yunseong approved these changes

2024-04-12 15:57 UTC, merged