feat: 기자재 상세 조회 기능 구현
jnu-resellers/resellers-fe pull request #26
Opened 2024-05-17 03:15 UTC by dxwwan

- 메인에서 id 받아오는 기능 추가 필요
- 체크 기능 삭제
- 사진별 상품 조회 기능 삭제

2024-05-17 06:12 UTC, 2yunseong requested changes
몇가지만 체크 부탁드림~~ 고생했으~

2024-05-17 06:12 UTC, 2yunseong commented on src/hooks/purchase/usePurchase.ts
안쓰면 삭제해도될듯??

2024-05-17 06:12 UTC, 2yunseong commented on src/components/Purchase/PurchaseDetails.tsx
> +  const fixedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
로직을 분리해볼까요?

2024-05-18 11:27 UTC, mlnwns approved these changes

2024-05-20 08:22 UTC, merged