feat: POST요청 및 응답 데이터 활용
jnu-resellers/resellers-fe pull request #63
Opened 2024-05-29 15:20 UTC by mlnwns

<img width="1280" alt="스크린샷 2024-05-30 오전 12 07 38" src="https://github.com/jnu-resellers/resellers-fe/assets/129190157/5c18e744-62f2-40d6-a286-be17bf9bb27d">  
  
- [x] 주문 신청 버튼 클릭 시 POST 요청을 통해 tradeId를 받아와서 거래 정보 페이지에서 GET 요청 하도록 수정
- [x] 경매 목록 페이지를 제외한 페이지에서 헤더에 판매하기, 경매 아이콘 보이도록 수정
- [x] 입금 완료 버튼 누르면 POST 요청하고 메인페이지에서 입금 완료된 상품 품절 표시
- [x] 입금 완료 버튼 누르면 메인페이지로 이동

2024-05-29 17:46 UTC, 2yunseong requested changes

2024-05-29 17:46 UTC, 2yunseong commented on src/components/Purchase/Purchase.tsx
> +  };
API 스키마보고 다시 적용시키세요
![image](https://github.com/jnu-resellers/resellers-fe/assets/56749516/86a6af5e-26c5-438c-87cc-cfbf2ac5ba2e)

2024-05-29 17:46 UTC, 2yunseong commented on src/components/Purchase/Purchase.tsx
> +  };
아까 진혁님이 설명하시지 않았나요?

2024-05-30 00:25 UTC, mlnwns commented on src/components/Purchase/Purchase.tsx
> +  };
진혁님이 설명하다가 마지막에 지금은 상세페이지당 기자재가 하나인 구조로 바껴서 productId랑 materialId 모두 동일한 값으로 전달하고 quantity는 1로 고정하면 된다고 하셔서 저렇게 작성하고 POST요청 해보니 tradeId 잘 반환되는거 확인했습니다. productId랑 materialId 받아와서 따로 주면 달라지는게 있을까요?

2024-05-30 00:36 UTC, mlnwns commented on src/components/Purchase/Purchase.tsx
> +  };
materialId와 productId 모두 동일하게 오고있어서 결과는 똑같을거같으나, 그래도 받은 값 바탕으로 이름 똑같게 보내는게 맞는거같아서 반영하도록 하겠습니다

2024-05-30 01:59 UTC, 2yunseong commented on src/components/Purchase/Purchase.tsx
> +  };
@mlnwns 
결과 똑같고 잘 나오는데 너가 왜 굳이 시비거냐? 라고 들리네요. 
아무리 캡스톤이라지만 너무 SI적 사고 아닌가요? ㅋㅋㅋㅋㅋㅋ
진짜로 하드코딩, 암묵적 비지니스 규칙으로 **돌아가기만 하는 되는 코드**만 작성하는 개발자가 정말 맞다고 생각하시는건가요...?

2024-05-30 02:04 UTC, mlnwns commented on src/components/Purchase/Purchase.tsx
> +  };
그런 의도는 아니었습니다! 제가 어제 진혁님 얘기를 이해한 부분과 윤성님이 이해한 부분이 다를 수 있을거같아서 잘 이해한게 맞는지 확인하려고 물어본거였습니다. 같은 값으로 주라고 이해를 했어서 코드를 저렇게 작성했었는데, 다시 생각해보니 결과는 같더라도 준 데이터 값을 사용해서 전달하는게 맞는거같다고 생각이 바껴서 저렇게 댓글 달았던겁니다..!

2024-05-30 02:12 UTC, mlnwns commented on src/components/Purchase/Purchase.tsx
> +  };
저는 기존에는 기자재가 한 상세페이지에 여러개 담겨있다가 지금은 한개의 상품만 담을 수 있기 때문에, 해당 값을 동일하게 주면 된다고 들었는데, 그러면 프론트에서 두 Id 값을 줄 게 아니라 백엔드에서 두 개의 Id중 하나를 삭제해야하는게 아닌가라는 생각을 했는데 그렇게 하지 않은 별다른 이유가 있는걸지 궁금해서 질문 드린겁니다!

2024-05-30 02:15 UTC, 2yunseong commented on src/components/Purchase/Purchase.tsx
> +  };
@mlnwns 
저는 API 상태를 모르는 상황에서 접근한거라 하위호환성 때문에 두 값을 같은 값으로 보내도 될거라고 말했던걸로 기억한거고 그 뒤에 진혁님이 와서 자세히 설명해주신거 같은데요, 제가 중간에 api 스키마 알아채고 두 값이 따로 온다는 걸 말씀을 안드렸나보네요!

2024-05-30 02:40 UTC, mlnwns commented on src/components/Purchase/Purchase.tsx
> +  };
@2yunseong 
어제 POST Request body 보니까 Id가 두개여서 왜 Id가 두개인지 진혁님한테 물어봤더니 이유가 정확히 이해 가지 않았지만, 결론적으로 두 Id 모두 같은 Id 값으로 보내면 된다고 해서 그 말 듣고 코드를 그렇게 작성했던건데,
윤성님 PR리뷰 이미지 보니까 두 Id 데이터가 따로 오고있어서 인지하고 이걸 반영하려고 보니 "왜 백엔드에서 이 Id중 하나를 안받도록 하지 않고 프론트에게 두 Id 모두 같은 값으로 요청하도록 하지?"라는 생각이 들어서 진혁님이 설명하신 부분에서 이 두 Id를 가지고 무언가 별도로 구별하는 로직이 있는건가 싶어서 이해하고 싶어서 질문 드렸던거고, 이 부분 관련해서는 진혁님에게 추가적으로 질문하도록 하겠습니다!

2024-05-30 07:53 UTC, 2yunseong commented on src/components/Purchase/Purchase.tsx
> +  };
아하 알겠습니다 코드 보니 잘 해결된거같네요

2024-05-30 07:59 UTC, 2yunseong approved these changes

2024-05-30 07:59 UTC, merged