fix: 경매 입찰 로직 수행시 오류와 성공 여부를 나타내지 않는 현상
jnu-resellers/resellers-fe pull request #68
Opened 2024-05-30 17:56 UTC by dxwwan

![image](https://github.com/jnu-resellers/resellers-fe/assets/77495584/b9733570-0803-497d-b449-111c5a5a3f0a)

mutatioinOption을 설정하는 과정에서 문제가 있었던 것 같습니다.
로직을 컴포넌트에 병합해 해당 오류를 수정했습니다.

2024-05-30 18:28 UTC, 2yunseong requested changes

2024-05-30 18:28 UTC, 2yunseong commented on src/components/Auction/AuctionPurchaseModal.tsx
> +                alert('현재가 보다 높은 입찰가를 설정해주세요.');
alert 문구와 조건이 이상하네요! 현재가 보다 높은 입찰가인데 0인지를비교하네요

2024-05-30 18:28 UTC, 2yunseong commented on src/components/Auction/AuctionPurchaseModal.tsx
> +              mutate({ auctionId, price: addedPrice || nowPrice });
addedPrice가 falsy한 값이면 사용자가 현재가로 입찰을 보내는건 사용자가 의도하지 않은 동작이라는 생각이드네요

2024-05-31 00:22 UTC, dxwwan commented on src/components/Auction/AuctionPurchaseModal.tsx
> +                alert('현재가 보다 높은 입찰가를 설정해주세요.');
> alert 문구와 조건이 이상하네요! 현재가 보다 높은 입찰가인데 0인지를비교하네요

addedPrice가 증가한 입찰가라 그렇습니다..! 로직을 다르게 바꿔보는게 좋을까요?

2024-05-31 00:23 UTC, dxwwan commented on src/components/Auction/AuctionPurchaseModal.tsx
> +              mutate({ auctionId, price: addedPrice || nowPrice });
> addedPrice가 falsy한 값이면 사용자가 현재가로 입찰을 보내는건 사용자가 의도하지 않은 동작이라는 생각이드네요

음 이해했습니다. 고민해보고 수정해볼게요!

2024-05-31 03:55 UTC, 2yunseong approved these changes

2024-05-31 03:56 UTC, merged